name: Collect HTV coins
on:
  schedule:
    - cron: "0 */1 * * *"
  workflow_dispatch:

env:
  HTV_EMAIL: "${{ secrets.HTV_EMAIL }}"
  HTV_PASSWORD: "${{ secrets.HTV_PASSWORD }}"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      
      - uses: styfle/cancel-workflow-action@0.9.0
        name: "Cancelling duplicate workflow runs"
        with:
          all_but_latest: true
          access_token: ${{ github.token }}
      
      - name: Install Dependencies
        run: |
          sudo apt upgrade -y && sudo apt update -y
          sudo apt install -y curl openssl jq
      
      - name: Create activity log
        run: date +'%s' > .github/activity
      
      - name: Collect Coins
        timeout-minutes: 1
        run: |
          chmod +x coins.sh
          ./coins.sh
      
      - name: Commit and Push
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}
          git add .
          git commit -m "Auto update: $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin HEAD:${{ github.ref }}