name: Collect HTV coins
on:
  schedule:
    - cron: "0 */1 * * *"
  workflow_dispatch:
  # Kích hoạt workflow khi có push để giữ repo active
  push:
    branches:
      - main

env:
  HTV_EMAIL: "${{ secrets.HTV_EMAIL }}"
  HTV_PASSWORD: "${{ secrets.HTV_PASSWORD }}"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: styfle/cancel-workflow-action@0.9.0
        with:
          all_but_latest: true
          access_token: ${{ github.token }}

      - name: Force weekly keep-alive
        run: |
          if [ $(date +%u) -eq 1 ]; then
            echo "keep-alive" >> keepalive.txt
          fi

      - name: Install Dependencies
        run: sudo apt update && sudo apt install -y curl openssl jq

      - name: Collect Coins
         timeout-minutes: 1
         run: |
           chmod +x coins.sh
           ./coins.sh

      - name: Commit changes
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add .
          git commit -m "Auto: Update session [$(date +%F)]" || exit 0

      - uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ github.token }}
          force: true